
project_id = "gocvjqljtcxtcrwvfwez"

[functions.scrape-events]
verify_jwt = false

[functions.generate-ical]
verify_jwt = false

[functions.generate-rss]
verify_jwt = false

[functions.scrape-meetup-events]
verify_jwt = false
